name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Exercise-1
      id: test-exercise-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Exercise-1
        setup-command: wget -O test_ex1.sh https://drive.google.com/uc?id=1HMmdSdFfMyutYd_CdvhRnvP52AzgW278
        command: "./test_ex1.sh"
        timeout: 5
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-EXERCISE-1_RESULTS: "${{steps.test-exercise-1.outputs.result}}"
      with:
        runners: test-exercise-1
